language: ruby
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0-preview2
  - head
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake test
